name: Use variable and secret context from environment

on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: dev  # Specify the environment (dev in this case)

    steps:
      - name: Use environment variable and secret context
        run: |
          echo "Environment: ${{ vars.STAGE }}"
          echo "Secret: ${{ secrets.SUPERSECRET }}"
      - name: Use global default context
        run: |
          echo "Github action owner: ${{ github.actor }}"
          echo "Github runner name: ${{ runner.name }}"
          echo "Github runner architecture: ${{ runner.arch }}"
      - name: Upload artifact for next job
        run: |
          echo "hello world" > hello.txt
      - uses: actions/upload-artifact@v4
        with:
          name: uploadhello
          path: hello.txt    

  retrieve:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Download artifact from previous job
        uses: actions/download-artifact@v4
        with:
          name: uploadhello
      - name: Read artifact content
        run: |
          cat hello.txt          