name: Use variable and secret context from environment

on:
    push:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: dev  # Specify the environment (dev in this case)

    steps:
      - name: Use environment variable and secret context
        run: |
          echo "Environment: ${{ vars.STAGE }}"
          echo "Secret: ${{ secrets.SUPERSECRET }}"