name: Use variable and secret context from repo and environment

on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use repo variable and secret context
        run: |
          echo "Repo Environment: ${{ vars.REPOLEVELSTAGE }}"
          echo "Repo Secret: ${{ secrets.REPOLEVELSECRET }}"  

    steps:
      environment: dev  # this step runs based on environment dev
      - name: Use environment variable and secret context
        run: |
          echo "Repo Environment: ${{ vars.STAGE }}"
          echo "Repo Secret: ${{ secrets.SUPERSECRET }}"  
