name: Use variable and secret context from repo

on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use repo variable and secret context
        run: |
          echo "Repo Environment: ${{ vars.REPOLEVELSTAGE }}"
          echo "Repo Secret: ${{ secrets.REPOLEVELSECRET }}"  