name: Use variable and secrets from repo and environment

on:
    workflow_dispatch:

jobs:
  repo-level:
    runs-on: ubuntu-latest

    steps:
      - name: Use repo variable and secret context
        run: |
          echo "Repo Stage: ${{ vars.REPOLEVELSTAGE }}"
          echo "Repo Secret: ${{ secrets.REPOLEVELSECRET }}"  

  env-level:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Use environment variable and secret context
        run: |
          echo "Env Stage: ${{ vars.STAGE }}"
          echo "Env Secret: ${{ secrets.SUPERSECRET }}"  
